server.port: 7009
app:
  eureka-server: localhost
  admin: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    
spring.application.name: gateway

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

spring.cloud.gateway:
  discovery.locator: 
    enabled: true
    lower-case-service-id: true

#spring.cloud.gateway.routes:
#- id: product-composite
#  uri: lb://product-composite
#  predicates:
#  - Path=/product-composite/**
#  filters:
#  - StripPrefix=1      
#  
#- id: admin
#  uri: lb://admin
#  predicates:
#  - Path=/admin/**
#  filters:
#  - StripPrefix=1
#  
#  
#- id: eureka-api
#  uri: http://${app.eureka-server}:8761
#  predicates:
#  - Path=/eureka/api/{segment}
#  filters:
#  - SetPath=/eureka/{segment}
#
#- id: eureka-web-start
#  uri: http://${app.eureka-server}:8761
#  predicates:
#  - Path=/eureka/web
#  filters:
#  - SetPath=/

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
  file:
    name: ./log/${spring.application.name}.log
---
spring.profiles: docker
server.port: 8080
app:
  eureka-server: eureka
  admin: admin
